# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thiết kế phần cứng
email: your-email@example.com

sass:
  style: :compressed  # Change to :expanded for debugging

permalink: /:year/:month/:day/:title.html

description: >- # this means to ignore newlines until "baseurl:"
  Nơi bạn có thể tìm thấy những kiến thức từ cơ bản đến nâng cao về thiết kế phần cứng.
  Schematic design-
  PCB Layout-
  Si/PI simulation-
  Measurement
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sipiviet.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CeramosHUT
github_username:  anhvanthe

future: true
debug: false

# Build settings
markdown: kramdown
#
permalink: pretty
future: true
highlighter: rouge
linenos: true
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
#
theme: minima
plugins:
  - jekyll-feed


paginate: 10
paginate_path: "/page:num/"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
